env:
  type: pusht
  visualization_width: 96
  visualization_height: 96
  obs_type: environment_state_agent_pos
  features:
    action:
      type: ACTION
      shape:
        - 2
    agent_pos:
      type: STATE
      shape:
        - 2
    environment_state:
      type: ENV
      shape:
        - 16