<<: !include base_diffusion.yaml
<<: !include envs/pusht_visual.yaml

job_name: pusht_diffusion_visual
policy:
  repo_id: OliverHausdoerfer/diffusion_pusht_v1
  type: diffusion
  optimizer_lr: 0.0002
  input_features:
    observation.image:
      type: VISUAL
      shape:
        - 3
        - 96
        - 96