<<: !include base_diffusion.yaml

job_name: train_diffusion_pusht_partial
env:
  type: pusht
  visualization_width: 96
  visualization_height: 96
  obs_type: environment_state_agent_pos_pixels
  features:
    action:
      type: ACTION
      shape:
        - 2
    agent_pos:
      type: STATE
      shape:
        - 2
    pixels:
      type: VISUAL
      shape:
        - 3
        - 96
        - 96
    environment_state:
      type: ENV
      shape:
        - 16
  CoverGreenT: true
dataset:
  repo_id: the-future-dev/pusht_image_keypoints
  image_transforms:
    enable: true
    tfs:
      CoverGreenT:
        weight: 1.0
        type: CoverGreenT
policy:
  repo_id: OliverHausdoerfer/diffusion_pusht_v1
  type: diffusion
  optimizer_lr: 0.0002
  partial_green_t_cover_processor: true
  input_features:
    observation.state:
      type: STATE
      shape:
        - 2
    observation.environment_state:
      type: ENV
      shape:
        - 16
    observation.image:
      type: VISUAL
      shape:
        - 3
        - 96
        - 96

