<<: !include train_diffusion_pusht_visual.yaml

job_name: train_diffusion_pusht_visual_coverTee
dataset:
  repo_id: the-future-dev/pusht_image_keypoints
  image_transforms:
    enable: true
    tfs:
      CoverGreenT:
        weight: 1.0
        type: CoverGreenT
