<<: !include base_diffusion.yaml
<<: !include envs/pusht.yaml

job_name: pusht_diffusion_keypoints
policy:
  repo_id: OliverHausdoerfer/diffusion_pusht_v1
  type: diffusion
  optimizer_lr: 0.0002
  input_features:
    observation.state:
      type: STATE
      shape:
        - 2
    observation.environment_state:
      type: ENV
      shape:
        - 16

